////////////////////MAIN

export const RETRY_ACTION = 'RETRY_ACTION'

///////////////POSTS

export const FETCH_POSTS = 'FETCH_POSTS'
export const FETCH_REMAINING_POSTS = 'FETCH_REMAINING_POSTS'
export const FETCH_REMAINING_POSTS_PENDING = 'FETCH_REMAINING_POSTS_PENDING'
export const FETCH_REMAINING_POSTS_FULFILLED = 'FETCH_REMAINING_POSTS_FULFILLED'
export const FETCH_POSTS_CANCELLED = 'FETCH_POSTS_CANCELLED'
export const FETCH_POSTS_PENDING = 'FETCH_POSTS_PENDING'
export const SELECT_POST = 'SELECT_POST'
export const SEARCH_POSTS_WITH_TERM = 'SEARCH_POSTS_WITH_TERM'
export const FETCH_POSTS_FULFILLED = 'FETCH_POSTS_FULFILLED'
export const FETCH_POSTS_REJECTED = 'FETCH_POSTS_REJECTED'

/////////////////CATEGORIES

export const FETCH_CATEGORIES = 'FETCH_CATEGORIES'
export const ADD_CATEGORY_FILTER = 'ADD_CATEGORY_FILTER'
export const REMOVE_CATEGORY_FILTER = 'REMOVE_CATEGORY_FILTER'
export const FETCH_CATEGORIES_PENDING = 'FETCH_CATEGORIES_PENDING'
export const FETCH_CATEGORIES_FULFILLED = 'FETCH_CATEGORIES_FULFILLED'
export const FETCH_CATEGORIES_REJECTED = 'FETCH_CATEGORIES_REJECTED'




////////////////////UI

export const TOGGLE_CATEGORIES = 'TOGGLE_CATEGORIES'
export const TOGGLE_SEARCH = 'TOGGLE_SEARCH'
export const TOGGLE_PLAYER = 'TOGGLE_PLAYER'
export const TOGGLE_EMAIL_FORM = 'TOGGLE_EMAIL_FORM'


/////////////////COMMENTS

export const ADD_COMMENT = 'ADD_COMMENT'
export const ADD_COMMENT_FULFILLED = 'ADD_COMMENT_FULFILLED'
export const ADD_COMMENT_REJECTED = 'ADD_COMMENT_REJECTED'

export const FETCH_COMMENTS = 'FETCH_COMMENTS'
export const FETCH_COMMENTS_PENDING = 'FETCH_COMMENTS_PENDING'
export const FETCH_COMMENTS_FULFILLED = 'FETCH_COMMENTS_FULFILLED'
export const FETCH_COMMENTS_BY_POST = 'FETCH_COMMENTS_BY_POST'
export const FETCH_COMMENTS_REJECTED = 'FETCH_COMMENTS_REJECTED'

////////////////////PAGES

export const FETCH_PAGES = 'FETCH_PAGES'
export const FETCH_PAGES_PENDING = 'FETCH_PAGES_PENDING'
export const FETCH_PAGES_FULFILLED = 'FETCH_PAGES_FULFILLED'
export const FETCH_PAGES_REJECTED = 'FETCH_PAGES_REJECTED'
export const ADD_PAGE_TO_STACK = 'ADD_PAGE_TO_STACK'
export const SELECT_PAGE = 'SELECT_PAGE'
export const SELECT_PAGE_WITH_LINK = 'SELECT_PAGE_WITH_LINK'
export const SELECT_MEMBER_PAGE = 'SELECT_MEMBER_PAGE'


/////////////////USERS

export const FETCH_USERS = 'FETCH_USERS'
export const FETCH_USERS_PENDING = 'FETCH_USERS_PENDING'
export const FETCH_USERS_FULFILLED = 'FETCH_USERS_FULFILLED'
export const FETCH_USERS_REJECTED = 'FETCH_USERS_REJECTED'

/////////////////PROFILE
export const SET_PROFILE = 'SET_PROFILE'

///////////////PLAYER

export const SET_PODCAST = 'SET_PODCAST'
export const SET_RADIO = 'SET_RADIO'
export const SET_PLAYER_STATUT = 'SET_PLAYER_STATUT'
export const LOAD_PLAYER = 'LOAD_PLAYER'
export const PLAY_PLAYER = 'PLAY_PLAYER'
export const RESUME_PLAYER = 'RESUME_PLAYER'
export const PAUSE_PLAYER = 'PAUSE_PLAYER'
export const STOP_PLAYER = 'STOP_PLAYER'
export const CLEAR_PLAYER = 'CLEAR_PLAYER'
export const FETCH_STREAM_INFO = 'FETCH_STREAM_INFO'
export const FETCH_STREAM_INFO_PENDING = 'FETCH_STREAM_INFO_PENDING'
export const FETCH_STREAM_INFO_FULFILLED = 'FETCH_STREAM_INFO_FULFILLED'
export const FETCH_STREAM_INFO_REJECTED = 'FETCH_STREAM_INFO_REJECTED'
export const STOP_FETCH_STREAM_INFO = 'STOP_FETCH_STREAM_INFO'


///////////////CONNECTION

export const CONNECTION_CHANGE = 'CONNECTION_CHANGE'
export const CONNECTED = 'CONNECTED'
export const DISCONNECTED = 'DISCONNECTED'

////////////////ERROR

export const RESET_ERROR = 'RESET_ERROR'


